name: Deploy to Windows Server

on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Caching Unity
      uses: actions/cache@v2
      with:
        path: ./Library
        key: Library-Culebritasss-windows
        restore-keys: |
          Library-Culebritasss-
          Library-
    - uses: game-ci/unity-builder@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        targetPlatform: StandaloneWindows64
        unityVersion: 2021.3.4f1
        buildMethod: "Editor.Builder.Build"
    - name: Debugging with tmate
      uses: mxschmitt/action-tmate@v3.11
    - uses: actions/upload-artifact@v2
      with:
        name: Build
        path: build
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: build-server
    - name: 📂 Pushing Build files
      uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
      with:
        ftp_host: ${{ secrets.FTP_HOST }}
        ftp_username: ${{ secrets.FTP_USERNAME }}
        ftp_password: ${{ secrets.FTP_PASSWORD }}
        local_source_dir: "."
        dist_target_dir: "Builds/Win-Server"
        delete: "true"
